### ISSUE TITLE
Graph Neural Network as MainNet

### ISSUE THREAD

**Issue by yhl48** [chrhenning/hypnettorch#1]
Hi, I was wondering if there is a way to use other types of main net not implemented in this library? For example, would it be possible to use a PyTorch Geometric network as the main net?

**Comment by chrhenning** [comment]
Hey, thanks for the question. You need as main network a network to which you can pass parameters when calling the ``forward`` method. Ideally, you use a network that implements the provided main network interface, such that all provided functionalities work properly. Unfortunately, there is (so far) no graph neural network provided in ``hypnettorch.mnets`` that implements this interface. So, you would need to implement your own main net. Hope that helps! Best, Christian
