### ISSUE TITLE
Incorrect dtype of weights tensor in getting_started tutorial

### ISSUE THREAD

**Issue by fszatkowski** [chrhenning/hypnettorch#2]
Hi,
First of all thanks for the great work on this library, it really helped me with my own research work. I noticed small bug in getting_started tutorial. If device is initally set to `cuda`, then later on when hypernetwork is used to generate main net weights this error occurs due to mismatch between types of image tensor `X` placed on cuda and weights tensor `W` which is placed on cpu.
![image](https://user-images.githubusercontent.com/39523414/157642870-cbdc1980-b67a-4856-a553-7a8328d09efc.png)
Simple fix is to move hypernetwork to device like this:
```python
hnet = HMLP(mnet.param_shapes, uncond_in_size=0, cond_in_size=8,
            layers=[100, 100], num_cond_embs=2).to(device)
```
Then it should work regardless if device is set to 'cpu' or 'cuda'.

**Comment by chrhenning** [comment]
Hey, thanks a lot for reporting the bug and providing the solution 👍 

I updated the notebook and hope it's fixed now (haven't tested on ``cuda``).

Best regards,
Christian
