### ISSUE TITLE
Training for  MNIST and FashionMNIST datasets.

### ISSUE THREAD

**Issue by AI4Math-ShanZhang** [chrhenning/hypnettorch#3]
Hi, would u help me to deal with the following issues:
when I follow the tutorial [https://github.com/chrhenning/hypnettorch/blob/master/hypnettorch/tutorials/getting_started.ipynb](url) and train the model on MNIST and FashionMNIST datasets, I got the 0% accuracy on both datasets.
I used the LeNet and  HMLP with parameters cond_in_size=8, layers=[100, 100].

Looking froward to your reply.
Thank you!

**Comment by chrhenning** [comment]
Hey, I just checkout the current master branch and reran the notebook. I get very similar results, see here:

![Screenshot 2022-06-08 at 09 05 55](https://user-images.githubusercontent.com/18127458/172553488-d8b0c2e4-3051-40df-a2dc-f94b0ce8d8a8.png)

@mariacer Could you have a look as well?

Best,
Christian

**Comment by AI4Math-ShanZhang** [comment]
hi, thanks for your help! I have already solved this issue.
