### ISSUE TITLE
Forward pass of the main network with a batch of weights 

### ISSUE THREAD

**Issue by sahandrez** [chrhenning/hypnettorch#4]
Hi, 

In the context of MLPs, I know that the forward pass of the hypernetwork can produce a batch of weights for the main network. But it seems that the forward pass of the main network is not able to process the batch of weights due to this assertion error: 
```
File "/Users/sahand.r/workspace/hypnettorch/hypnettorch/mnets/mlp.py", line 561, in forward
    assert(len(weights) == len(self.param_shapes))
AssertionError
```
A naive approach would be to loop over the batch and do independent forward passes of the main network, but is there a more efficient approach for this? 

Thanks!

**Comment by chrhenning** [comment]
Hey, unfortunately, there is currently no way that is more efficient other than looping over the batch. I know that for a plain MLP, it would be rather easy to implement a forward pass that can handle a batch of weights and a batch of inputs. However, with all the additional options that our MLP class offers, one would need to be very careful in implementing this and it would also lead to inconsistencies, as other main network implementation wouldn't allow receiving a batch of weights as input.

Though, if you implement a plain MLP that can handle a batch of weights, would be great if you could share it 😊

Best,
Christian

**Comment by sahandrez** [comment]
Hi, thanks for the clarification! Sure, if I ever get to implement it, I will share it! 
Best, 
Sahand
