### ISSUE TITLE
Hypernetwork for Fourier neural operators

### ISSUE THREAD

**Issue by Tariq97** [chrhenning/hypnettorch#6]
Hello developers,

Thank you for providing this library. 
I would like to know if you have plans to develop similar method for fourier neural operator as main network?

Fourier neural operators cannot take meta data as input and in a way it can be incorporated by making the Weight matrix as hyperparameter. Do you think u can look into it.

Thanks

**Comment by chrhenning** [comment]
Hey @Tariq97 ,

Thanks for the request. I'm currently don't have the time to actively develop new core for this package. But feel free to make a PR 😉

Best wishes,
Christian
