### ISSUE TITLE
Hypernetwork for CNNs

### ISSUE THREAD

**Issue by FZuffer** [chrhenning/hypnettorch#8]
Hi,

Thank you so much for this great repository. It has great features and has enabled me to carry out many of my work.
I was wondering if any implementation has been done for standard CNN architectures. I've been using the MLP and HMLP so far and I'm looking for any direction on how this could be extended to a CNN architecture.

Thanks in advance.

**Comment by chrhenning** [comment]
Hey, thank you :)

There are multiple CNN architectures implemented as main network, e.g., [Lenet](https://hypnettorch.readthedocs.io/en/latest/mnets.html#lenet), [Resnet32](https://hypnettorch.readthedocs.io/en/latest/mnets.html#resnet), or [WRN](https://hypnettorch.readthedocs.io/en/latest/mnets.html#wide-resnet).

There are multiple hypernet architecture that you can use for CNNs (also checkout the [tutorials](https://hypnettorch.readthedocs.io/en/latest/tutorials.html)). I recommend using a [ChunkedHMLP](https://hypnettorch.readthedocs.io/en/latest/hnets.html#chunked-mlp-hypernetwork).

Hope that helps :)

**Comment by FZuffer** [comment]
Hi,

Thank you for the quick reply.

In my case, I was hoping to create my own simple CNN architecture as the main network (like how we could customize it for simple MLPs). It seems like I have to write my own CNN main network?

Thank you.

**Comment by chrhenning** [comment]
Hey, yes, you have to implement [this](https://hypnettorch.readthedocs.io/en/latest/mnets.html#main-network-interface) interface to write your custom main network (at least if you want to have full compatibility with all functionalities provided by this library).

Though, you can always instantiate a hyper network by just passing a list of tensor shapes, and it will produce weights which you can feed to your own CNN in whatever way you consider most easy to implement ;)

**Comment by FZuffer** [comment]
Hi,
Great! Thank you so much for this suggestion. Appreciate it a lot. :)
